image: java:7-jdk-alpine

stages:
  - build


build:
  script:
    - ./gradlew build
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 month
  variables:
    GIT_SUBMODULE_STRATEGY: recursive