before_script:
  - which java
  - which javac

build:
  script:
    - ./gradlew build
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 month
  variables:
    GIT_SUBMODULE_STRATEGY: recursive